<a href="https://colab.research.google.com/github/AbiaAlvesReis/Projeto-IA-2022-01/blob/main/AMMStensorFlowKerasF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import everything
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.preprocessing import StandardScaler
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Create a DataFrame
mega_df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/dados testes /mega.xlsx', parse_dates=True, index_col=1)

In [ ]:
mega_df.head()

lottery  ball_01  ball_02  ball_03  ball_04  ball_05  ball_06
date                                                                     
1996-03-11      1.0     41.0      5.0      4.0     52.0     30.0     33.0
1996-03-18      2.0      9.0     39.0     37.0     49.0     43.0     41.0
1996-03-25      3.0     36.0     30.0     10.0     11.0     29.0     47.0
1996-04-01      4.0      6.0     59.0     42.0     27.0      1.0      5.0
1996-04-08      5.0      1.0     19.0     46.0      6.0     16.0      2.0

 “tail()” retorna as últimas cinco observações.

In [ ]:
mega_df.tail()

lottery  ball_01  ball_02  ball_03  ball_04  ball_05  ball_06
date                                                                     
2022-05-14   2481.0      1.0     37.0     36.0     21.0      8.0     27.0
2022-05-18   2482.0     32.0      1.0     57.0     44.0     35.0     45.0
2022-05-21   2483.0     54.0     49.0     34.0     38.0     40.0     20.0
2022-05-25   2484.0     59.0     36.0     41.0     54.0     14.0     11.0
2022-05-28   2485.0     60.0     12.0     38.0     47.0      5.0     32.0

Total de registros

In [ ]:
print(mega_df.shape)

(2485, 7)


In [ ]:
mega_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2485 entries, 1996-03-11 to 2022-05-28
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   lottery  2485 non-null   float64
 1   ball_01  2485 non-null   float64
 2   ball_02  2485 non-null   float64
 3   ball_03  2485 non-null   float64
 4   ball_04  2485 non-null   float64
 5   ball_05  2485 non-null   float64
 6   ball_06  2485 non-null   float64
dtypes: float64(7)
memory usage: 155.3 KB


Retorna a contagem, média, desvio padrão, valores mínimo e máximo e os quantis dos dados

In [ ]:
mega_df.describe()

lottery      ball_01      ball_02      ball_03      ball_04  \
count  2485.000000  2485.000000  2485.000000  2485.000000  2485.000000   
mean   1243.000000    30.465191    30.151710    30.734406    30.752918   
std     717.502033    17.302279    17.367138    17.328347    17.248985   
min       1.000000     1.000000     1.000000     1.000000     1.000000   
25%     622.000000    16.000000    15.000000    16.000000    16.000000   
50%    1243.000000    30.000000    31.000000    31.000000    31.000000   
75%    1864.000000    45.000000    45.000000    45.000000    45.000000   
max    2485.000000    60.000000    60.000000    60.000000    60.000000   

          ball_05      ball_06  
count  2485.00000  2485.000000  
mean     30.55493    30.372233  
std      17.17453    17.173908  
min       1.00000     1.000000  
25%      15.00000    16.000000  
50%      31.00000    30.000000  
75%      45.00000    45.000000  
max      60.00000    60.000000

In [ ]:
mega_df.drop('lottery', inplace=True, axis=1)

In [ ]:
#df.drop('date', inplace=True, axis=1)

In [ ]:
mega_df.head()

ball_01  ball_02  ball_03  ball_04  ball_05  ball_06
date                                                            
1996-03-11     41.0      5.0      4.0     52.0     30.0     33.0
1996-03-18      9.0     39.0     37.0     49.0     43.0     41.0
1996-03-25     36.0     30.0     10.0     11.0     29.0     47.0
1996-04-01      6.0     59.0     42.0     27.0      1.0      5.0
1996-04-08      1.0     19.0     46.0      6.0     16.0      2.0

A entrada tem que ser semelhantes, média de 0 e 1, redimensionando os dados

In [ ]:
scaler = StandardScaler().fit(mega_df.values)
transformed_dataset = scaler.transform(mega_df.values)
transformed_mega_df = pd.DataFrame(data=transformed_dataset, index=mega_df.index)

In [ ]:
transformed_mega_df.head()

0         1         2         3         4         5
date                                                                  
1996-03-11  0.608991 -1.448527 -1.543124  1.232035 -0.032318  0.153040
1996-03-18 -1.240849  0.509587  0.361653  1.058077  0.724769  0.618957
1996-03-25  0.319953 -0.008737 -1.196801 -1.145395 -0.090555  0.968394
1996-04-01 -1.414271  1.661419  0.650256 -0.217617 -1.721205 -1.477668
1996-04-08 -1.703309 -0.642245  0.881138 -1.435325 -0.847642 -1.652387

Variáveis

In [ ]:
# Todos Sorteios
number_of_rows = mega_df.values.shape[0]
number_of_rows

2485

In [ ]:
# Quantidade de jogos para a previsão
window_length = 7
window_length 

7

In [ ]:
# contagem
number_of_features = mega_df.values.shape[1]
number_of_features

6

In [ ]:
X = np.empty([ number_of_rows - window_length, window_length, number_of_features], dtype=float)


In [ ]:
y = np.empty([ number_of_rows - window_length, number_of_features], dtype=float)


X e y dos dados modelo kerasLSTM

In [ ]:
for i in range(0, number_of_rows-window_length):
    X[i] = transformed_mega_df.iloc[i : i+window_length, 0 : number_of_features]
    y[i] = transformed_mega_df.iloc[i+window_length : i+window_length+1, 0 : number_of_features]

In [ ]:
X.shape

(2478, 7, 6)

In [ ]:
y.shape

(2478, 6)

Amostra em escala de 7 jogos




In [ ]:
X[0]

array([[ 0.60899083, -1.44852726, -1.54312392,  1.23203531, -0.0323177 ,
         0.15304004],
       [-1.24084876,  0.50958717,  0.36165334,  1.05807703,  0.72476949,
         0.61895672],
       [ 0.31995339, -0.00873724, -1.19680078, -1.14539452, -0.09055517,
         0.96839423],
       [-1.41427122,  1.66141919,  0.65025595, -0.21761702, -1.7212045 ,
        -1.47766835],
       [-1.70330866, -0.64224485,  0.88113804, -1.43532498, -0.84764236,
        -1.65238711],
       [-0.66277389,  0.56717877, -1.36996235, -1.02942233, -0.49821751,
         0.96839423],
       [ 1.47610314,  0.45199557, -0.56187503, -0.62351968, -1.60472955,
        -1.47766835]])

In [ ]:
y[0]

array([ 1.30268067, -0.75742805,  0.41937386, -1.55129717,  0.9577194 ,
        0.38599838])

In [ ]:
X[1]

array([[-1.24084876,  0.50958717,  0.36165334,  1.05807703,  0.72476949,
         0.61895672],
       [ 0.31995339, -0.00873724, -1.19680078, -1.14539452, -0.09055517,
         0.96839423],
       [-1.41427122,  1.66141919,  0.65025595, -0.21761702, -1.7212045 ,
        -1.47766835],
       [-1.70330866, -0.64224485,  0.88113804, -1.43532498, -0.84764236,
        -1.65238711],
       [-0.66277389,  0.56717877, -1.36996235, -1.02942233, -0.49821751,
         0.96839423],
       [ 1.47610314,  0.45199557, -0.56187503, -0.62351968, -1.60472955,
        -1.47766835],
       [ 1.30268067, -0.75742805,  0.41937386, -1.55129717,  0.9577194 ,
         0.38599838]])

In [ ]:
y[1]

array([ 1.41829565,  0.73995358,  1.45834327,  1.34800749, -1.31354217,
        1.72550884])

Modelagem iniando RNN

In [ ]:
# Recurrent Neural Netowrk (RNN) with Long Short Term Memory (LSTM)
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional, Dropout
batch_size = 60

In [ ]:
# Initialising the RNN
model = Sequential()
# Adding the input layer and the LSTM layer
model.add(Bidirectional(LSTM(60,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a first Dropout layer
model.add(Dropout(0.2))
# Adding a second LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a second Dropout layer
model.add(Dropout(0.2))
# Adding a third LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a fourth LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = False)))
# Adding a fourth Dropout layer
model.add(Dropout(0.2))
# Adding the first output layer
model.add(Dense(59))
# Adding the last output layer
model.add(Dense(number_of_features))

In [ ]:
from tensorflow import keras
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate=0.0001), loss ='mse', metrics=['accuracy'])

In [ ]:
model.fit(x=X, y=y, batch_size=100, epochs=300, verbose=2)

Epoch 1/300
25/25 - 25s - loss: 1.0002 - accuracy: 0.1868 - 25s/epoch - 1s/step
Epoch 2/300
25/25 - 9s - loss: 0.9978 - accuracy: 0.1893 - 9s/epoch - 370ms/step
Epoch 3/300
25/25 - 9s - loss: 0.9968 - accuracy: 0.1812 - 9s/epoch - 366ms/step
Epoch 4/300
25/25 - 9s - loss: 0.9959 - accuracy: 0.1844 - 9s/epoch - 367ms/step
Epoch 5/300
25/25 - 9s - loss: 0.9955 - accuracy: 0.1860 - 9s/epoch - 371ms/step
Epoch 6/300
25/25 - 9s - loss: 0.9952 - accuracy: 0.1776 - 9s/epoch - 368ms/step
Epoch 7/300
25/25 - 9s - loss: 0.9944 - accuracy: 0.1860 - 9s/epoch - 370ms/step
Epoch 8/300
25/25 - 9s - loss: 0.9946 - accuracy: 0.1840 - 9s/epoch - 370ms/step
Epoch 9/300
25/25 - 9s - loss: 0.9941 - accuracy: 0.1796 - 9s/epoch - 368ms/step
Epoch 10/300
25/25 - 9s - loss: 0.9937 - accuracy: 0.1868 - 9s/epoch - 373ms/step
Epoch 11/300
25/25 - 9s - loss: 0.9934 - accuracy: 0.1848 - 9s/epoch - 371ms/step
Epoch 12/300
25/25 - 9s - loss: 0.9932 - accuracy: 0.1872 - 9s/epoch - 368ms/step
Epoch 13/300
25/25 - 9s - 

Resultado do 100 ultimos jogos da Mega-Sena

In [ ]:
mega_df_predicit = mega_df.tail(6)



In [ ]:
mega_df_predicit.drop([mega_df_predicit.index[-1]],axis=0, inplace=True)
mega_df_predicit

In [ ]:
prediction = mega_df.tail(1)
prediction

ball_01  ball_02  ball_03  ball_04  ball_05  ball_06
date                                                            
2022-05-28     60.0     12.0     38.0     47.0      5.0     32.0

In [ ]:
mega_df_predicit = np.array(mega_df_predicit)
mega_df_predicit

array([[31., 56.,  6.,  4., 50.,  9.],
       [ 1., 37., 36., 21.,  8., 27.],
       [32.,  1., 57., 44., 35., 45.],
       [54., 49., 34., 38., 40., 20.],
       [59., 36., 41., 54., 14., 11.]])

In [ ]:
scaled_to_predict = scaler.transform(mega_df_predicit)
scaled_to_predict


array([[ 0.03091596,  1.48864439, -1.42768287, -1.55129717,  1.13243182,
        -1.24471001],
       [-1.70330866,  0.39440397,  0.30393281, -0.56553358, -1.31354217,
        -0.19639747],
       [ 0.08872344, -1.67889367,  1.51606379,  0.76814656,  0.25886968,
         0.85191506],
       [ 1.36048816,  1.08550318,  0.18849177,  0.42023   ,  0.55005706,
        -0.60407457],
       [ 1.6495256 ,  0.33681237,  0.59253543,  1.34800749, -0.96411732,
        -1.12823084]])

In [ ]:
y_pred = model.predict(np.array([scaled_to_predict]))
resulta=scaler.inverse_transform(y_pred).astype(int)[0]
#print("Numeros previstos:", scaler.inverse_transform(y_pred).astype(int)[0])
print("Numeros previstos:", resulta)



Numeros previstos: [24 27 32 32 21 36]


In [ ]:
prediction = mega_df.tail(7)
prediction = np.array(prediction)
prediction_final = prediction[0]
print("Numeros sorteados:", prediction_final)

Numeros sorteados: [21. 10. 35. 20. 17. 15.]
